datasets:
  audio_train:
    data_type: images
    build_info:
      image_path: ../Minigpt_Med/LVLM-Med/1Vindata/vindr-cxr-images/images/train
      ann_path: ../Minigpt_Med/LVLM-Med/1Vindata/vindr-cxr-images/annotations/train/global_labels_train_v2.json
      audio_path: medlvlm/datasets/example_datasets/audio_datasets